src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Date__c</fullName>
        <label>Appointment Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Working_Hours_End__c</fullName>
        <label>Working Hours End</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Working_Hours_Start__c</fullName>
        <label>Working Hours Start</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppointmentTriggerHandler.cls
public with sharing class AppointmentTriggerHandler {
    public void checkAppointment(List<Appointment__c> appointments) {
        Set<Id> doctorsIds = new Set<Id>();
        for (Appointment__c appointment : appointments) {
            doctorsIds.add(appointment.Doctor__c);
        }
        List<Doctor__c> doctors = [
                SELECT Name, Working_Hours_Start__c,Working_Hours_End__c, (SELECT Appointment_Date__c FROM Appointments__r)
                FROM Doctor__c
                WHERE Id IN :doctorsIds
        ];
        for (Appointment__c appointment : appointments) {
            for (Doctor__c doctor : doctors) {
                if (appointment.Doctor__c == doctor.Id) {
                    for (Appointment__c docsAppointment : doctor.Appointments__r) {
                        if (docsAppointment.Appointment_Date__c == appointment.Appointment_Date__c) {
                            appointment.addError(System.Label.The_doctor_already_has_an_appointment);
                        }
                    }
                }
            }
        }
    }
}